### ISSUE TITLE
Providing trained models

### ISSUE THREAD

**Issue by frezaeix** [asharakeh/bayes-od-rc#3]
Hi @asharakeh, 
Thanks for publishing your code. Is it possible for you to provide trained models that you used for your published paper?

In addition, it seems that there is a bug with the demo  for loading bdd labels. However, I ran it on kitti dataset and it worked.

**Comment by asharakeh** [comment]
@frezaeix Thanks for looking at the code. Ill take a look at the bug you mentioned.

I probably cannot upload trained models directly on git. If you can let me know which model you need I can definitely send it via link to dropbox or google drive.

**Comment by frezaeix** [comment]
> @frezaeix Thanks for looking at the code. Ill take a look at the bug you mentioned.
> 
> I probably cannot upload trained models directly on git. If you can let me know which model you need I can definitely send it via link to dropbox or google drive.

Thank you for your quick response. It would be great if you can upload both of your BayesOD trained models on BDD and COCO.

**Comment by asharakeh** [comment]
@frezaeix 
**BDD checkpoint:** https://drive.google.com/file/d/1hlz_q6DYjHbFLTwJyCqFS6L7qg7Lj6Sy/view?usp=sharing

**COCO checkpoint:** https://drive.google.com/file/d/1gUcJrCXfPa9kwYRV1lmjzvlpMYV3uPkG/view?usp=sharing

COCO requires you to write a coco dataset handler, which might be difficult. Also, I will be providing pytorch code for BayesOD on coco and other datasets in a few months.

**Comment by frezaeix** [comment]
@asharakeh Thank you! Cool!
